[pytest]
addopts = --maxfail=2 -v --html=reports/reports.html

markers =
    api: Marks API-related tests
    high: Marks high-priority tests
    medium: Marks medium-priority tests
    low: Marks low-priority tests
    critical: Marks critical severity tests
    file: Marks file upload/download tests
